### ISSUE TITLE
keyboard selection and forms

### ISSUE THREAD

**Issue by dalf** [autocompletejs/autocomplete.js#40]
Setup : 
* a form with a input text and a submit button.

Use case : 
* set the focus on the input text
* select an autocomplete choice with the keyboard (arrow keys)
* press enter

What happen : 
* the form is submit with the value before the selection (if I didn't mess up with the installation see bellow)

What is expected : 
* the form is submitted with the selected value

See : https://al-f.net/searx/?q=autocomplete-js ([source code](https://github.com/dalf/searx/tree/simple/searx/static/themes/simple))

**Comment by baptistedonaux** [comment]
@dalf Are you sure that the form is really sent because if I see the last released source code, I can see a ```preventDefault``` call.

* https://github.com/autocompletejs/autocomplete.js/blob/v2.4.0/src/autocomplete.ts#L155
* https://github.com/autocompletejs/autocomplete.js/blob/v2.4.0/src/autocomplete.ts#L170

I can't reproduce the same fail. Do you have others informations to reproduce the issue ?

**Comment by ezkimo** [comment]
I have the same issue with HTML5 forms with validation constraints. Reproducable on current versions of Microsoft Edge, Mozilla Firefox and Google Chrome browsers. Safari was not tested.

`AutoComplete(
    {
        ...
    },
    'input[name="zipcode"]'
);
`

No special options where set. Just a url for the request and a limit. When iterating through the results with the up and down keys and then pressing enter, to select an item, the form triggers the invalid event. If all elements are valid the form submits. The _Select method is not executed.

After a deep dive into the code I found out, that the default keyboard mapping KeyUpAndDown_down ist triggered before Enter. So Enter never gets fired, because the key code 13 is not set in the conditions of KeyUpAndDown_down. 

A small hotfix for this issue to get it working correctly.

```js
var mapping = Object.assign(AutoComplete.defaults.KeyboardMappings, {
    'KeyUpAndDown_down' : {
        Conditions : [
            {
                Is : 38,
                Not : false
            },
            {
                Is : 40,
                Not : false
            },
            {
                Is : 13,
                Not : false
            }
        ],
        Callback : function(event) {
            event.preventDefault();
        },
        Operator : 1,
        Event : 0
    }
});
AutoComplete(
    {
        KeyboardMappings : mapping
    },
    'input[name="zipcode"]'
);
```

Now you can iterate through the results with the up and down keys and select an item with enter.

**Comment by dalf** [comment]
I've just made a quick example : https://github.com/dalf/autocomple-test

**Comment by baptistedonaux** [comment]
This issue has been resolve into ```2.6.3```. Sorry for the response time !
