### ISSUE TITLE
Show results even with empty input on focus event

### ISSUE THREAD

**Issue by karamanolev** [autocompletejs/autocomplete.js#45]
I've been using this library successfully and it looks great, but now I need to show some results (more like recommended searches) without any input - just on focus. After I read the source, it seems the the only event where the search is performed is on keyup for alphanumeric characters and so what I want is impossible. If there already are results, then they will show up on focus, but not if the input is empty. Is there a way to do this currently? If not - is it possible to add support for that use-case?

**Comment by baptistedonaux** [comment]
Your question is old but I give you my response. All can be overridden.

If you rewrite the method `_Focus` you can managed `input` selection.
If you play in the same time with `_Render` method, technically you can add another DOM element into `<div>` which will be brother of `<ul>`.

All can be overriden but few different comportment can be hard to develop because it can be required to rewrite all methods of library...

You're welcome :godmode:
