### ISSUE TITLE
Why put attr, attrClass and domCreate globally?

### ISSUE THREAD

**Issue by scotv** [autocompletejs/autocomplete.js#8]
Hi @baptistedonaux,

I just wondering why you put `attr()`, `attrClass()` and `domCreate()` globally, instead of inside the `AutoComplete` object?

Thanks again for the lite autocomplte.js, I am using it.

**Comment by baptistedonaux** [comment]
Hi,
When I released the first version of Autocomplete.js, I would wanted  a really lite script ( < 4KB). With the features added in 1.1, 1.2, ... I would wanted with script < 4KB. So, I have created few alias method to limit size but this hack reached these limits.

For next rewrite (2.* releases), I won't use alias method and remove this size limit because it's a brake for features development.
